name: Deploy to Cloud Run

on:
  push:
    branches:
      - develop
      - hotfix/**
      - epic/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 30

    env:
      # stage
      STAGE: dev
      # GCP settings
      GCP_REGION: ${{ secrets.GCP_REGION }}
      # GCP service account credentials
      SERVICE_ACCOUNT_CREDENTIAL_JSON: ${{ secrets.SERVICE_ACCOUNT_CREDENTIAL_JSON }}
      # DB credentials
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      CLOUD_SQL_CONNECTION_NAME: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
      # application settings
      ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
      APPLICATION_NAME: ${{ secrets.APPLICATION_NAME }}
      # batch settings
      BATCH_ARTIFACT_REGISTRY: ${{ secrets.BATCH_ARTIFACT_REGISTRY }}
      BATCH_NAME: ${{ secrets.BATCH_NAME }}
      # Jumpbox settings
      JUMPBOX_INSTANCE_NAME: ${{ secrets.JUMPBOX_INSTANCE_NAME }}
      JUMPBOX_ZONE: ${{ secrets.JUMPBOX_ZONE }}
      # Apollo studio
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_GRAPH_REF: ${{ secrets.APOLLO_GRAPH_REF }}

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Set up Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies
      run: |
          pnpm install --frozen-lockfile

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@8254fb75a33b976a221574d287e93919e6a36f70 # v2.1.6
      with:
        credentials_json: ${{ env.SERVICE_ACCOUNT_CREDENTIAL_JSON }}

    - name: pnpm db:generate
      env:
        DATABASE_URL: postgresql://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@localhost:5432/${{ env.DB_NAME }}
      run: |
        echo "--- Connecting to DB via jumpbox ---"
        gcloud compute ssh ${{ env.JUMPBOX_INSTANCE_NAME }} \
          --tunnel-through-iap \
          --zone=${{ env.JUMPBOX_ZONE }} \
          --quiet -- -N -L 5432:localhost:5432 &
        SSH_PID=$!
        sleep 60
        for i in {1..5}; do
          pg_isready -h localhost -p 5432 -d ${{ env.DB_NAME }} && break
          sleep 60
        done

        echo "--- Running prisma generate ---"
        pnpm db:generate

        echo "Killing SSH tunnel"
        kill $SSH_PID

    - name: pnpm gql:generate
      run: pnpm gql:generate

    - name: Debug Apollo env
      run: |
        if [ -z "$APOLLO_KEY" ]; then
          echo "❌ APOLLO_KEY is missing"
        else
          echo "✅ APOLLO_KEY is set"
        fi

        if [ -z "$APOLLO_GRAPH_REF" ]; then
          echo "❌ APOLLO_GRAPH_REF is missing"
        else
          echo "✅ APOLLO_GRAPH_REF is set"
        fi
      env:
        APOLLO_KEY: ${{ env.APOLLO_KEY }}
        APOLLO_GRAPH_REF: ${{ env.APOLLO_GRAPH_REF }}

    - name: Install and Publish via Rover CLI
      env:
        APOLLO_KEY: ${{ env.APOLLO_KEY }}
        APOLLO_GRAPH_REF: ${{ env.APOLLO_GRAPH_REF }}
      run: |
        curl -sSL https://rover.apollo.dev/nix/latest | sh
        export PATH="$HOME/.rover/bin:$PATH"
        rover graph publish --schema ./docs/schema.graphql

    - name: pnpm build
      run: pnpm build

    - name: Configure Docker for GCP Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY }}
        gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

    - name: Build Docker image
      run: |
        pnpm dotenvx run -- docker build --no-cache -t ${{ env.ARTIFACT_REGISTRY }}/${{ env.APPLICATION_NAME }}:latest .

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@8254fb75a33b976a221574d287e93919e6a36f70 # v2.1.6
      with:
        credentials_json: ${{ env.SERVICE_ACCOUNT_CREDENTIAL_JSON }}

    - name: Push Docker image to Artifact Registry
      run: |
        docker push ${{ env.ARTIFACT_REGISTRY }}/${{ env.APPLICATION_NAME }}:latest

    - name: Deploy Internal API to Cloud Run
      id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2' # v2.8.1
      with:
        service: ${{ env.APPLICATION_NAME }}
        image: ${{ env.ARTIFACT_REGISTRY }}/${{ env.APPLICATION_NAME }}:latest
        region: ${{ env.GCP_REGION }}

    - name: Build Docker image for batch job
      run: |
        docker build -t ${{ env.BATCH_ARTIFACT_REGISTRY }}/${{ env.BATCH_NAME }}:latest -f Dockerfile.batch .

    - name: Push Docker image for batch job to Artifact Registry
      run: |
        docker push ${{ env.BATCH_ARTIFACT_REGISTRY }}/${{ env.BATCH_NAME }}:latest

    - name: Cleanup SSH Key
      if: always()
      run: rm -f ~/.ssh/google_compute_engine ~/.ssh/google_compute_engine.pub
